# Dataset
train_db_name: oxford-iiit-pet 
train_db_kwargs:
   split: trainaug
   batch_size: 16
val_db_name: oxford-iiit-pet 
val_db_kwargs:
   batch_size: 16
num_workers: 4

mean: [0.4893, 0.4767, 0.4253]
std: [0.2326, 0.2234, 0.2276]
# Model
backbone: 'resnet50'
backbone_kwargs:
   dilated: True
head: 'deeplab'
pretraining: '/cs/student/msc/dsml/2023/mdavudov/ADL/MaskContrast/RESULTS/CATSNDOGS_supseg_PICA/checkpoint.pth.tar' #/path/to/checkpoint.pth.tar # Change this.

# Optimizer
epochs: 60
scheduler: step
scheduler_kwargs:
   lr_decay_rate: 0.1
   lr_decay_epochs: [25]

optimizer: sgd 
optimizer_kwargs:
   lr: 0.1
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
freeze_batchnorm: 'all'
